### ISSUE TITLE
No Activity found to handle Intent

### ISSUE THREAD

**Issue by rajam1215** [ShadowNinja/CallRecorder#2]
When all recording is done. Recorded file not open, It give error.

App give error. when click on stored file for play,,,,sound player not open....how to solve  

No Activity found to handle Intent is come 
```
12-16 16:05:16.856 26277-26277/com.callrecorder3dee E/URI: content://com.callrecorder3dee.android.fileprovider/external-recordings/20171216155053_919815512900.3gpp
12-16 16:05:16.862 26277-26277/com.callrecorder3dee E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: com.callrecorder3dee, PID: 26277
                                                                      android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW typ=audio/3gpp flg=0x1 }
                                                                          at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1915)
                                                                          at android.app.Instrumentation.execStartActivity(Instrumentation.java:1629)
                                                                          at android.app.Activity.startActivityForResult(Activity.java:3927)
                                                                          at android.app.Activity.startActivityForResult(Activity.java:3888)
                                                                          at android.app.Activity.startActivity(Activity.java:4211)
                                                                          at android.app.Activity.startActivity(Activity.java:4179)
                                                                          at com.callrecorder3dee.RecordingsAdapter.startPlayExternal(RecordingsAdapter.java:141)
                                                                          at com.callrecorder3dee.RecordingsAdapter.access$000(RecordingsAdapter.java:21)
                                                                          at com.callrecorder3dee.RecordingsAdapter$1.onClick(RecordingsAdapter.java:76)
                                                                          at com.android.internal.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1108)
```

**Comment by ShadowNinja** [comment]
It seems like Android thinks that you just don't have any apps installed that know how to handle the 3gpp format.

This part of the code could definitely use some work though, it doesn't seem to reliably find all of the applications that can handle the file type.

**Comment by rajam1215** [comment]
private void startPlayExternal(String fileName) throws IOException {
        DocumentFile file = FileHelper.getStorageFile(context)
                .findFile(fileName);
        Uri uri = Uri.parse(file.getUri().toString());
        Intent intent = new Intent(Intent.ACTION_VIEW, uri);
        intent.setDataAndType(uri,"audio/3gpp");
        context.startActivity(intent);
    }

I solve this with that code,  In RecordingsAdapter Class

**Comment by rajam1215** [comment]
But In some new devices .3gpp format not run. Give file format error. coz of not supported 3gpp file.

But .AMR format run in every devices, you can say 95% devices support this format, can you use that and some solution with that.
